source 'http://rubygems.org'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'magnetism', :path => '../../'

group :development do
  gem 'mongrel', '1.2.0.pre2'
  gem 'linecache19'
end

group :test do
  gem 'shoulda', '>= 2.11.3'
  gem 'rspec', '>= 2.5.0', :require => false
  gem 'rspec-rails', '>= 2.5.0', :require => false
  gem 'ruby-debug19'
  gem 'database_cleaner', '~> 0.6.0'
  gem 'factory_girl', '~> 1.3.2'
  gem 'cover_me', '~> 1.0.0.rc4'
  gem 'webrat', '~> 0.7.2'
end
